config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'user_lists/follow_list/:user_id', to: 'user_lists#follow_list', as: 'user_lists_follow_list'
  get 'user_lists/followed_list/:user_id', to: 'user_lists#followed_list', as: 'user_lists_followed_list'
  root to: 'homes#top'

  resources :users, only: [:show, :edit, :update] do
    get 'mylist', to: 'mylists#target_index'
    resource :follows, only: [:create, :destroy] do
    get 'followings', to: 'follows#followings'
    get 'followers', to: 'follows#followers'
   end
  end

  resources :flogs do
    resource :likes, only: [:create, :destroy]
  end

  resources :movies
  resources :mylists

  get '/user/check', to: 'users#check'
  patch 'user/withdraw', to: 'users#withdraw'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :wrriten_flog
  
end

app/models/my_list.rb
class MyList < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :introduction, length: {maximum: 100}

  def active_for_authentication?
    super && (is_active == true)
  end


  def follow_set(user_id)
    follow.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follow.find_by(followed_id: user_id).destroy
  end

  def following?(user_id)
    followings.include?(user_id)
  end

  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true

  attachment :image
  has_many :wrriten_flogs, dependent: :destroy
  has_many :my_lists, dependent: :destroy
  has_many :likes, dependent: :destroy

  # has_manyでメソッド化している。defのようなもの

  has_many :follow, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :follow, source: :followed
  has_many :followers, through: :follow, source: :follower

end

app/models/wrriten_flog.rb
class WrritenFlog < ApplicationRecord

  validates :score, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
  
  validates :review, presence: true, length: {maximum: 200}
  

  belongs_to :user
  has_many :likes, dependent: :destroy
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/flogs_controller.rb
class FlogsController < ApplicationController
  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def index
    @user = current_user
    @flogs = @user.wrriten_flogs.reverse_order.page(params[:page]).per(6)
  end

  def show
   @search = Tmdb::Movie.detail(params[:id])
   @movie_title = @search["title"]
   @movie_poster = @search["poster_path"]
   @movie_story = @search["overview"]

   @flogs = WrritenFlog.where(movie_id: params[:id]).reverse_order.page(params[:page]).per(6)

  end

  def new
    @wrriten_flog = WrritenFlog.new
    @search = Tmdb::Movie.detail(params[:id])
    @movie_title = @search["title"]
    @movie_poster = @search["poster_path"]
    @movie_story = @search["overview"]
  end

  def create
    @flog = WrritenFlog.new(wrriten_flog_params)
    @flog.movie_id = params[:wrriten_flog][:movie_id].to_i
    @flog.user_id = current_user.id
    @flog.save
    my_list = MyList.find_by(movie_id: @flog.movie_id , user_id: @flog.user_id)
    my_list.destroy if my_list.present?

    redirect_to flogs_path
  end

  def edit
    @flog = WrritenFlog.find(params[:id])
  end

  def update
    flog = WrritenFlog.find(params[:id])
    flog.update(wrriten_flog_params)
    redirect_to flogs_path
  end

  def destroy
    flog = WrritenFlog.find(params[:id])
    flog.destroy
    redirect_to flogs_path
  end

  private
  def wrriten_flog_params
    params.require(:wrriten_flog).permit(:score, :review, :movie_id, :movie_title, :movie_poster)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  
  def create
    current_user.follow_set(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def top
      @keywords = params[:looking_for]

    if @keywords.present?

      @search = Tmdb::Search.movie(@keywords)
      # 変換処理
      @conversion = JSON.parse(@search.to_json)
      # view へ 変数を渡す
      @search_results = @conversion["table"]["results"]
      #@sample_search_results = 結果

    end

      render "top"
  end
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @flog = WrritenFlog.find(params[:flog_id])
    like = current_user.likes.new(user_id: current_user.id, wrriten_flog_id: params[:flog_id])
    like.save
  end

  def destroy
    @flog = WrritenFlog.find(params[:flog_id])
    like = current_user.likes.find_by(user_id: current_user.id, wrriten_flog_id: params[:flog_id])
    like.destroy
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def show
    @search = Tmdb::Movie.detail(params[:id])
    @movie_title = @search["title"]
    @movie_poster = @search["poster_path"]
    @movie_story = @search["overview"]

  end
end

app/controllers/mylists_controller.rb
class MylistsController < ApplicationController
  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def index
    @user = current_user
    @mylists = @user.my_lists.reverse_order.page(params[:page]).per(8)
  end

  def target_index
    @user = User.find(params[:user_id])
    @mylists = @user.my_lists.reverse_order.page(params[:page]).per(8)
  end

  def create
    @search = Tmdb::Movie.detail(params[:id])
    @mylist = current_user.my_lists.build(movie_id: @search.id ,movie_title: @search["title"], movie_poster: @search["poster_path"])
    @mylist.save

    redirect_to mylists_path
  end

  def destroy
    mylist = MyList.find(params[:id])
    mylist.destroy
    redirect_to mylists_path
  end

end

app/controllers/user_lists_controller.rb
class UserListsController < ApplicationController
  def follow_list
    @user = User.find(params[:user_id])
    @follow_user = Follow.where(follower_id: params[:user_id])
  end

  def followed_list
    @user = User.find(params[:user_id])
    @followed_user = Follow.where(followed_id: params[:user_id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")


  def show
   @user = User.find(params[:id])
   @flogs = WrritenFlog.where(movie_id: params[:id]).reverse_order.page(params[:page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: '会員情報の更新が完了しました。'
    else
      render :edit
    end
  end

  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end

    private

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flogs_helper.rb
module FlogsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/mylists_helper.rb
module MylistsHelper
end

app/helpers/user_lists_helper.rb
module UserListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follow/follow.js.erb
$('#follow_buttons_<%= @user.id %>').html("<%= j(render "users/follow", user: @user) %>");

app/views/follow/unfollow.js.erb
$('#follow_buttons_<%= @user.id %>').html("<%= j(render "users/follow", user: @user) %>");

app/views/likes/create.js.erb
$('#favorite_buttons_<%= @flog.id %>').html("<%= j(render "flogs/like", flog: @flog) %>");

app/views/likes/destroy.js.erb
$('#favorite_buttons_<%= @flog.id %>').html("<%= j(render "flogs/like", flog: @flog) %>");

app/views/mylists/index.html.erb
<div class="container-fluid">
  <h3 class="text-center m-5">MtList</h3>
  <div class="row">
  <div class="col-lg-2">
   <%= render 'users/my_profile', user: @user %>
  </div>
  <div class="col-lg-10">
    <div class="row">
      <% @mylists.each do |mylist| %>
      <div class="col-lg-3 mb-2">
        <div class="mylist card p-3">
          <div class="text-center image-area">
            <%= link_to movie_path(mylist.movie_id) do %>
            <%= image_tag("https://image.tmdb.org/t/p/w154/" + mylist.movie_poster ) %>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-title text-center ">
              <h6><%= mylist.movie_title %></h6>
            </div>
            <div class="mylist-delete-button">
              <%= link_to mylist_path(mylist.id), method: :delete do %>
              <%= image_tag("trash-3.svg") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% sleep 0.3 %>
      <% end %>
    </div>
  </div>
 </div>
</div>
<%= paginate @mylists %>

app/views/mylists/target_index.html.erb
<div class="container-fluid">
  <h3 class="text-center m-5"><%= @user.nickname%>さんのMtList</h3>
  <div class="row">
    <div class="col-lg-2">
      <div class="card profile-card">
        <div class="card-body">
          <div class="text-center"><%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "00582.png", size:'100x100'  ,class: 'rounded-circle mb-3'%></div>
          <h5 class="card-title text-center"><%= @user.nickname %></h5>
          <p class="card-text text-center"><%= @user.introduction %></p>
            <div class="follow-button">
              <%= link_to user_lists_follow_list_path(@user.id) do %>
               <%= @user.follow.count %>フォロー中
              <% end %>
            </div>
            <div class="follow-button">
              <%= link_to user_lists_followed_list_path(@user.id) do %>
               <%= @user.followed.count %>フォロワー
              <% end %>
            </div>
            <div class="profile-button">
              <% if current_user%>
                <% if current_user.following?(@user) %>
                  <%= link_to "フォロー中", user_follows_path(@user.id), method: :delete, class:"btn btn-primary" %>
                <% else %>
                  <%= link_to "フォローする", user_follows_path(@user.id), method: :post, class:"btn btn-light" %>
                <% end %>
              <% else %>
             <% end %>
           </div>
        </div>
      </div>
    </div>
  <div class="col-lg-10">
    <div class="row">
      <% @mylists.each do |mylist| %>
      <div class="col-lg-3 mb-2">
        <div class="mylist card p-3">
          <div class="text-center image-area">
            <%= link_to movie_path(mylist.movie_id) do %>
            <%= image_tag("https://image.tmdb.org/t/p/w154/" + mylist.movie_poster ) %>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-title text-center ">
              <h6><%= mylist.movie_title %></h6>
            </div>
          </div>
        </div>
      </div>
      <% sleep 0.3 %>
      <% end %>
    </div>
  </div>
 </div>
</div>
<%= paginate @mylists %>