config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'user_lists/follow_list/:user_id', to: 'user_lists#follow_list', as: 'user_lists_follow_list'
  get 'user_lists/followed_list/:user_id', to: 'user_lists#followed_list', as: 'user_lists_followed_list'
  root to: 'homes#top'

  resources :users, only: [:show, :edit, :update] do
    get 'mylist', to: 'mylists#target_index'
    resource :follows, only: [:create, :destroy] do
    get 'followings', to: 'follows#followings'
    get 'followers', to: 'follows#followers'
   end
  end

  resources :flogs do
    resource :likes, only: [:create, :destroy]
  end

  resources :movies
  resources :mylists

  get '/user/check', to: 'users#check'
  patch 'user/withdraw', to: 'users#withdraw'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :introduction, length: {maximum: 100}

  def active_for_authentication?
    super && (is_active == true)
  end


  def follow_set(user_id)
    follow.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follow.find_by(followed_id: user_id).destroy
  end

  def following?(user_id)
    followings.include?(user_id)
  end

  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true

  attachment :image
  has_many :wrriten_flogs, dependent: :destroy
  has_many :my_lists, dependent: :destroy
  has_many :likes, dependent: :destroy

  # has_manyでメソッド化している。defのようなもの

  has_many :follow, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :follow, source: :followed
  has_many :followers, through: :follow, source: :follower

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_user
    @user = find(params[:id])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_active == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")


  def show
   @user = User.find(params[:id])
   @flogs = WrritenFlog.where(movie_id: params[:id]).reverse_order.page(params[:page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: '会員情報の更新が完了しました。'
    else
      render :edit
    end
  end

  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end

    private

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if current_user%>
 <% if current_user.following?(user) %>
  <%= link_to "フォロー中", user_follows_path(user.id), method: :delete, class:"btn btn-primary", remote: true %>
 <% else %>
  <%= link_to "フォローする", user_follows_path(user.id), method: :post, class:"btn btn-light", remote: true %>
 <% end %>
 <% else %>
<% end %>

app/views/users/_my_profile.html.erb
     <div class="card profile-card">
       <div class="card-body">
          <div class="text-center"><%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "00582.png", size:'100x100'  ,class: 'rounded-circle mb-3'%></div>
          <h5 class="card-title text-center"><%= user.nickname %></h5>
          <p class="card-text text-center"><%= user.introduction %></p>
          <div class="follow">
            <div class="follow-button">
              <%= link_to user_lists_follow_list_path(user.id) do %>
               <%= user.follow.count %>フォロー中
              <% end %>
            </div>
            <div class="follow-button">
              <%= link_to user_lists_followed_list_path(user.id) do %>
               <%= user.followed.count %>フォロワー
              <% end %>
            </div>
          </div>
        </div>
       </div>

app/views/users/check.html.erb
<div class="container-fluid mt-5">
	<div class="row">
		<div class="col-lg-8 offset-lg-2 text-center">
			<h3 class="section-ttl mb-4">本当に退会しますか？</h3>
			<h4 class="text-center mb-4">退会するとこれまでのFlogやMyListsを見ることができなくなります。<br>退会する場合は、「退会する」をクリックしてください。</h4>
			<div class="flex justify-around mt2">
				<%= link_to "Top画面に戻る", root_path, class: "btn btn-primary" %>
				<%= link_to "退会する", user_withdraw_path, method: :patch, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？", class: "btn btn-danger" %>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 offset-lg-3 text-center">
      <div>
        <h1 class="m-5">プロフィール編集</h1>
      </div>
      <div>
       <%= form_with model:@user, local:true do |f| %>
       <div class="mb-3">
        <div>
         <label for="inputName">名前</label>          
        </div>
        <div>
         <%= f.text_field :nickname, autofocus: true, id:"inputName",class:"form-control", placeholder:"名前"%>           
        </div>
       </div>
       <div>
         <div class="mb-3">
          <label for="inputImage">プロフィール画像</label>
          <%= attachment_image_tag @user, :image, :fill, 60, 60, fallback: "00582.png", size:'100x100' %>
         </div>
         <div class="mb-3">
          <%= f.attachment_field :image, id:"inputImage", placeholder: "プロフィール画像" %>
         </div>
       </div>
       <div class="mb-3">
         <label for="inputMailadress">メールアドレス</label>
         <%= f.text_field :email, id:"inputemail",class:"form-control",placeholder: "メールアドレス" %>
       </div>
       <div class="mb-3">
         <label for="inputMailadress">自己紹介</label>
         <%= f.text_area :introduction, id:"inputIntroduction",class:"form-control", placeholder: "自己紹介",rows: 5, maxlemgth: "200" %>
       </div>

       <div class="mb-3">
         <%= f.submit "変更を保存",class:"btn btn-primary" %>
         <%= link_to "退会する", user_check_path,class:"btn btn-danger" %>
       </div>
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <h3 class="text-center m-5"><%= @user.nickname%>さんのFlogs</h3>
  <div class="row">
    <div class="col-lg-2">
     <div class="card profile-card">
       <div class="card-body">
          <div class="text-center"><%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "00582.png", size:'100x100'  ,class: 'rounded-circle mb-3'%></div>
          <h5 class="card-title text-center"><%= @user.nickname %></h5>
          <p class="card-text text-center"><%= @user.introduction %></p>
            <div class="follow-button">
              <%= link_to user_lists_follow_list_path(@user.id) do %>
               <%= @user.follow.count %>フォロー中
              <% end %>
            </div>
            <div class="follow-button">
              <%= link_to user_lists_followed_list_path(@user.id) do %>
               <%= @user.followed.count %>フォロワー
              <% end %>
            </div>
           <div id="follow_buttons_<%= @user.id %>", class="profile-button">
             <%= render "users/follow", user: @user %>
           </div>
           <p class="profile-button">
             <%= link_to "MyLists", user_mylist_path(@user.id), class:"btn btn-light" %>
           </p>
        </div>
       </div>
     </div>
    <div class="col-lg-10">
     <%= render 'flogs/flog', user: @user %>
     <%= paginate @flogs%>
   </div>
 </div>
</div>