config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'user_lists/follow_list/:user_id', to: 'user_lists#follow_list', as: 'user_lists_follow_list'
  get 'user_lists/followed_list/:user_id', to: 'user_lists#followed_list', as: 'user_lists_followed_list'
  root to: 'homes#top'

  resources :users, only: [:show, :edit, :update] do
    get 'mylist', to: 'mylists#target_index'
    resource :follows, only: [:create, :destroy] do
    get 'followings', to: 'follows#followings'
    get 'followers', to: 'follows#followers'
   end
  end

  resources :flogs do
    resource :likes, only: [:create, :destroy]
  end

  resources :movies
  resources :mylists

  get '/user/check', to: 'users#check'
  patch 'user/withdraw', to: 'users#withdraw'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :wrriten_flog
  
end

app/models/my_list.rb
class MyList < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :introduction, length: {maximum: 100}

  def active_for_authentication?
    super && (is_active == true)
  end


  def follow_set(user_id)
    follow.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follow.find_by(followed_id: user_id).destroy
  end

  def following?(user_id)
    followings.include?(user_id)
  end

  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true

  attachment :image
  has_many :wrriten_flogs, dependent: :destroy
  has_many :my_lists, dependent: :destroy
  has_many :likes, dependent: :destroy

  # has_manyでメソッド化している。defのようなもの

  has_many :follow, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :follow, source: :followed
  has_many :followers, through: :follow, source: :follower

end

app/models/wrriten_flog.rb
class WrritenFlog < ApplicationRecord

  validates :score, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
  
  validates :review, presence: true, length: {maximum: 200}
  

  belongs_to :user
  has_many :likes, dependent: :destroy
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/flogs_controller.rb
class FlogsController < ApplicationController
  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def index
    @user = current_user
    @flogs = @user.wrriten_flogs.reverse_order.page(params[:page]).per(6)
  end

  def show
   @search = Tmdb::Movie.detail(params[:id])
   @movie_title = @search["title"]
   @movie_poster = @search["poster_path"]
   @movie_story = @search["overview"]

   @flogs = WrritenFlog.where(movie_id: params[:id]).reverse_order.page(params[:page]).per(6)

  end

  def new
    @wrriten_flog = WrritenFlog.new
    @search = Tmdb::Movie.detail(params[:id])
    @movie_title = @search["title"]
    @movie_poster = @search["poster_path"]
    @movie_story = @search["overview"]
  end

  def create
    @flog = WrritenFlog.new(wrriten_flog_params)
    @flog.movie_id = params[:wrriten_flog][:movie_id].to_i
    @flog.user_id = current_user.id
    @flog.save
    my_list = MyList.find_by(movie_id: @flog.movie_id , user_id: @flog.user_id)
    my_list.destroy if my_list.present?

    redirect_to flogs_path
  end

  def edit
    @flog = WrritenFlog.find(params[:id])
  end

  def update
    flog = WrritenFlog.find(params[:id])
    flog.update(wrriten_flog_params)
    redirect_to flogs_path
  end

  def destroy
    flog = WrritenFlog.find(params[:id])
    flog.destroy
    redirect_to flogs_path
  end

  private
  def wrriten_flog_params
    params.require(:wrriten_flog).permit(:score, :review, :movie_id, :movie_title, :movie_poster)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  
  def create
    current_user.follow_set(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def top
      @keywords = params[:looking_for]

    if @keywords.present?

      @search = Tmdb::Search.movie(@keywords)
      # 変換処理
      @conversion = JSON.parse(@search.to_json)
      # view へ 変数を渡す
      @search_results = @conversion["table"]["results"]
      #@sample_search_results = 結果

    end

      render "top"
  end
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @flog = WrritenFlog.find(params[:flog_id])
    like = current_user.likes.new(user_id: current_user.id, wrriten_flog_id: params[:flog_id])
    like.save
  end

  def destroy
    @flog = WrritenFlog.find(params[:flog_id])
    like = current_user.likes.find_by(user_id: current_user.id, wrriten_flog_id: params[:flog_id])
    like.destroy
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def show
    @search = Tmdb::Movie.detail(params[:id])
    @movie_title = @search["title"]
    @movie_poster = @search["poster_path"]
    @movie_story = @search["overview"]

  end
end

app/controllers/mylists_controller.rb
class MylistsController < ApplicationController
  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def index
    @user = current_user
    @mylists = @user.my_lists.reverse_order.page(params[:page]).per(8)
  end

  def target_index
    @user = User.find(params[:user_id])
    @mylists = @user.my_lists.reverse_order.page(params[:page]).per(8)
  end

  def create
    @search = Tmdb::Movie.detail(params[:id])
    @mylist = current_user.my_lists.build(movie_id: @search.id ,movie_title: @search["title"], movie_poster: @search["poster_path"])
    @mylist.save

    redirect_to mylists_path
  end

  def destroy
    mylist = MyList.find(params[:id])
    mylist.destroy
    redirect_to mylists_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")


  def show
   @user = User.find(params[:id])
   @flogs = WrritenFlog.where(movie_id: params[:id]).reverse_order.page(params[:page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: '会員情報の更新が完了しました。'
    else
      render :edit
    end
  end

  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end

    private

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flogs_helper.rb
module FlogsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/mylists_helper.rb
module MylistsHelper
end

app/helpers/user_lists_helper.rb
module UserListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flogs/_flog.html.erb
    <div class="row">
        <% user.wrriten_flogs.each do |flog| %>
          <div class="col-lg-4 mb-2">
            <div class="flog-item card p-3">
              <div class="text-center image-area">
                <%= link_to movie_path(flog.movie_id) do %>
                  <%= image_tag("https://image.tmdb.org/t/p/w154/" + flog.movie_poster ) %>
                <% end %>
              </div>
              <div class="card-body">
                <div class="card-title text-center flog-title ">
                  <h6><%= flog.movie_title %></h6>
                      <div class="card-text mb-3 text-center">
                        <span id="star-rate-<%= flog.id %>"></span>
                        <script>
                          $('#star-rate-<%= flog.id %>').raty({
                            size: 36,
                            starOff: "<%= asset_path('star-off.png') %>",
                            starOn: "<%= asset_path('star-on.png') %>",
                            starHalf: "<%= asset_path('star-half.png') %>",
                            half: true,
                            readOnly: true,
                            score: <%= flog.score %>
                          });
                        </script>
                      </div>
                  </div>
                  <div class="main-content">
                    <p class="card-text flog-review"><%= flog.review %></p>
                    <div class="card-text"><%= flog.likes.count %> いいね </div>
                    <span class="card-text"><%= flog.created_at.strftime('%Y/%m/%d') %></span>
                    <div>
                      <%= link_to edit_flog_path(flog.id) do %>
                        <%= image_tag("edit.svg") %>
                      <% end %>
                      <%= link_to flog_path(flog.id), method: :delete do %>
                        <%= image_tag("trash-3.svg") %>
                      <% end %>
                    </div>
                 </div>
                <% sleep 0.3 %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
   

app/views/flogs/_like.html.erb
  <%if current_user%>
    <% if flog.liked_by?(current_user) %>
    <p>
      <%= link_to flog_likes_path(flog.id), method: :delete, class:'likes', remote: true do %>
      ♥　<%= flog.likes.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to flog_likes_path(flog.id), method: :post, remote: true do %>
      ♡　<%= flog.likes.count %>
      <% end %>
    </p>
    <% end %>
  <%else%>
     <%= link_to new_user_session_path do %>
      ♡　<%= flog.likes.count %>
      <% end %>
  <%end%>

app/views/flogs/edit.html.erb
<div class="container-fluid m-5">
  <div class="row">
    <div class="text-center">
      <h1 class="mb-3">Flogを編集</h1>
        <div>
          <%= image_tag("https://image.tmdb.org/t/p/w200/" + @flog.movie_poster) %>
        </div>
        <div class="mt-3 mb-3">
          <%= form_with model:@flog, url:"/flogs/#{@flog.id}", local:true do |f| %>
            <div class="field mb-4" id="star","">
              <%= f.hidden_field :score, id: :review_star %>
              <script>
                $('#star').raty({
                  size     : 36,
                  score : '<%= @flog.score %>',
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  scoreName: 'wrriten_flog[score]',
                  half: true,
                });
              </script>
            </div>
            <div class="mb-3">
             <%= f.text_area :review, :size=>"55x7"  %>
            </div>
            <div class="mb-3">
              <%= f.submit 'Flog!' %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/flogs/index.html.erb
<div class="container-fluid">
  <h3 class="text-center  m-5">Flogs</h3>
  <div class="row">
    <div class="col-lg-2">
     <%= render 'users/my_profile', user: @user %>
    </div>
    <div class="col-lg-10">
     <%= render 'flogs/flog', user: @user %>
     <%= paginate @flogs%>
    </div>
</div>
</div>

app/views/flogs/new.html.erb
<div class="container-fluid m-5">
  <div class="row">
    <div class="col-lg-6 offset-lg-3 text-center">
        <h1 class="movie-title"><%= @movie_title %></h1>
      <div class="mb-4">
        <p><%= image_tag("https://image.tmdb.org/t/p/w200/" + @movie_poster) %></p>
      </div>
        <%= form_with model:@wrriten_flog, url:'/flogs', :method => 'post', local:true do |f| %>

          <div class="field mb-4" id="star","">
              <%= f.hidden_field :score, id: :review_star %>
              <script>
                $('#star').raty({
                  size     : 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  scoreName: 'wrriten_flog[score]',
                  half: true,
                });
              </script>
          </div>
          <div class="mb-3">
          <%= f.text_area :review, :size=>"55x7", class:"form-control", rows: 5  %>
          <%= f.hidden_field :movie_id, :value => @search[:id] %>
          <%= f.hidden_field :movie_title, :value => @movie_title %>
          <%= f.hidden_field :movie_poster, :value => @movie_poster %>
          </div>
          <div>
          <%= f.submit 'Flog!', class:"btn btn-light" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/flogs/show.html.erb
<div class="container-fluid">
 <h3 class="text-center m-5">Flogs</h3>
  <div class="row">
    <div class="col-lg-2 text-center">
      <div class="card profile-card">
        <div class="card-body">
          <div class="text-center mb-4"><%= image_tag("https://image.tmdb.org/t/p/w154/" + @movie_poster ) %></div>
          <h5 class="card-title"><%= @movie_title %></h5>
        </div>
      </div>
    </div>
    <div class="col-lg-10">
      <div class="row">
        <% @flogs.each do |flog| %>
        <div class="col-lg-4 mb-2">
          <div class="else-flog-item card p-3">
            <div class="">
              <%if current_user%>
                <% if current_user.id == flog.user.id %>
                <%= link_to flogs_path do %>
                　<%= attachment_image_tag flog.user, :image, :fill, 60, 60, fallback: "00582.png", size:'60x60',class: 'rounded-circle' %>
                <%= flog.user.nickname %>
                <% end %>
                <% else %>
                <%= link_to user_path(flog.user) do %>
                　<%= attachment_image_tag flog.user, :image, :fill, 60, 60, fallback: "00582.png",size:'60x60',class: 'rounded-circle' %>
                <%= flog.user.nickname %>
                <% end %>
                <% end %>
              <%else%>
              <%= link_to user_path(flog.user) do %>
                　<%= attachment_image_tag flog.user, :image, :fill, 60, 60, fallback: "00582.png",size:'60x60',class: 'rounded-circle' %>
                <%= flog.user.nickname %>
                <% end %>

              <% end %>

            </div>
            <div class="card-body">
              <div class="card-text mb-3">
                <span id="star-rate-<%= flog.id %>"></span>
                <script>
                  $('#star-rate-<%= flog.id %>').raty({
                    size: 36,
                    starOff: "<%= asset_path('star-off.png') %>",
                    starOn: "<%= asset_path('star-on.png') %>",
                    starHalf: "<%= asset_path('star-half.png') %>",
                    half: true,
                    readOnly: true,
                    score: <%= flog.score %>
                  });
                </script>
              </div>
              <p class="card-text else-review"><%= flog.review %></p>
              <div class="card-text"><%= flog.created_at.strftime('%Y/%m/%d') %></div>
              <div id="favorite_buttons_<%= flog.id %>", class="card-text">
                <%= render "flogs/like", flog: flog %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= paginate @flogs %>

app/views/homes/top.html.erb
<div  class="container">
  <div class="text-center">
    <h1 class="mt-5 mb-5">Flog</h1>
    <div class="search-form mb-5">
      <%= form_tag(root_path, method: :get) do %>
      <%= search_field_tag :looking_for, nil, placeholder: '映画を調べる',class: "search-field" %>
      <%= image_submit_tag("search-2.svg", class: "ml-2")  %>
      <% end %>
    </div>
    <div class="row">
        <% if @search_results.present? %>
        <% @search_results.each do |result| %>
        <div class="col-lg-3 mb-2">
            <div class="result card">
                <div class="text-center">
                  <%= link_to movie_path(result["table"]["id"],class: "link" ) do %>
                  <p><%= image_tag("https://image.tmdb.org/t/p/w154/" + result["table"]["poster_path"]) %></p>
                </div>
                <div class="card-body">
                  <p><%= result["table"]["title"]%></p>
                </div>
                   <% end %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
    </div>
 </div><!--text-center-->
</div><!--container-->

app/views/movies/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 offset-lg-2 text-center">
      <div class="movie-infomation">
        <h1><%= @movie_title %></h1>
        <div class="about-movie">
          <p class="movie_poster"><%= image_tag("https://image.tmdb.org/t/p/w200/" + @movie_poster) %></p>
          <p class="story"><%=  @movie_story %></p>
          <% if current_user  %>
            <% if current_user.wrriten_flogs.where(movie_id: params[:id]).exists? %>
    
            <% elsif current_user.my_lists.where(movie_id: params[:id]).exists? %>
              <%= link_to "Flog", new_flog_path(id: @search.id), class:"btn btn-light" %>
            <% else %>
              <%= link_to "Flog", new_flog_path(id: @search.id), class:"btn btn-light" %>
              <%= link_to "MyList", mylists_path(id: @search.id), method: :post, class:"btn btn-light" %>
            <% end %>
          <%else%>
              <%= link_to "Flog", new_user_session_path, class:"btn btn-light" %>
              <%= link_to "MyList", new_user_session_path, class:"btn btn-light" %>
    
          <%end%>
              <%= link_to "他の人のFlogを見る", flog_path(@search.id), class:"btn btn-light"%>
        </div>
      </div>    
    </div>
   </div>    
  </div>