config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'user_lists/follow_list/:user_id', to: 'user_lists#follow_list', as: 'user_lists_follow_list'
  get 'user_lists/followed_list/:user_id', to: 'user_lists#followed_list', as: 'user_lists_followed_list'
  root to: 'homes#top'

  resources :users, only: [:show, :edit, :update] do
    get 'mylist', to: 'mylists#target_index'
    resource :follows, only: [:create, :destroy] do
    get 'followings', to: 'follows#followings'
    get 'followers', to: 'follows#followers'
   end
  end

  resources :flogs do
    resource :likes, only: [:create, :destroy]
  end

  resources :movies
  resources :mylists

  get '/user/check', to: 'users#check'
  patch 'user/withdraw', to: 'users#withdraw'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :wrriten_flog
  
end

app/models/my_list.rb
class MyList < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :introduction, length: {maximum: 100}

  def active_for_authentication?
    super && (is_active == true)
  end


  def follow_set(user_id)
    follow.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follow.find_by(followed_id: user_id).destroy
  end

  def following?(user_id)
    followings.include?(user_id)
  end

  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true

  attachment :image
  has_many :wrriten_flogs, dependent: :destroy
  has_many :my_lists, dependent: :destroy
  has_many :likes, dependent: :destroy

  # has_manyでメソッド化している。defのようなもの

  has_many :follow, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :follow, source: :followed
  has_many :followers, through: :follow, source: :follower

end

app/models/wrriten_flog.rb
class WrritenFlog < ApplicationRecord

  validates :score, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
  
  validates :review, presence: true, length: {maximum: 200}
  

  belongs_to :user
  has_many :likes, dependent: :destroy
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/flogs_controller.rb
class FlogsController < ApplicationController
  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def index
    @user = current_user
    @flogs = @user.wrriten_flogs.reverse_order.page(params[:page]).per(6)
  end

  def show
   @search = Tmdb::Movie.detail(params[:id])
   @movie_title = @search["title"]
   @movie_poster = @search["poster_path"]
   @movie_story = @search["overview"]

   @flogs = WrritenFlog.where(movie_id: params[:id]).reverse_order.page(params[:page]).per(6)

  end

  def new
    @wrriten_flog = WrritenFlog.new
    @search = Tmdb::Movie.detail(params[:id])
    @movie_title = @search["title"]
    @movie_poster = @search["poster_path"]
    @movie_story = @search["overview"]
  end

  def create
    @flog = WrritenFlog.new(wrriten_flog_params)
    @flog.movie_id = params[:wrriten_flog][:movie_id].to_i
    @flog.user_id = current_user.id
    @flog.save
    my_list = MyList.find_by(movie_id: @flog.movie_id , user_id: @flog.user_id)
    my_list.destroy if my_list.present?

    redirect_to flogs_path
  end

  def edit
    @flog = WrritenFlog.find(params[:id])
  end

  def update
    flog = WrritenFlog.find(params[:id])
    flog.update(wrriten_flog_params)
    redirect_to flogs_path
  end

  def destroy
    flog = WrritenFlog.find(params[:id])
    flog.destroy
    redirect_to flogs_path
  end

  private
  def wrriten_flog_params
    params.require(:wrriten_flog).permit(:score, :review, :movie_id, :movie_title, :movie_poster)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def top
      @keywords = params[:looking_for]

    if @keywords.present?

      @search = Tmdb::Search.movie(@keywords)
      # 変換処理
      @conversion = JSON.parse(@search.to_json)
      # view へ 変数を渡す
      @search_results = @conversion["table"]["results"]
      #@sample_search_results = 結果

    end

      render "top"
  end
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @flog = WrritenFlog.find(params[:flog_id])
    like = current_user.likes.new(user_id: current_user.id, wrriten_flog_id: params[:flog_id])
    like.save
  end

  def destroy
    @flog = WrritenFlog.find(params[:flog_id])
    like = current_user.likes.find_by(user_id: current_user.id, wrriten_flog_id: params[:flog_id])
    like.destroy
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")

  def show
    @search = Tmdb::Movie.detail(params[:id])
    @movie_title = @search["title"]
    @movie_poster = @search["poster_path"]
    @movie_story = @search["overview"]

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'themoviedb-api'
  Tmdb::Api.key("de02a1639be95fbfec0058fd054d9de5")
  Tmdb::Api.language("ja")


  def show
   @user = User.find(params[:id])
   @flogs = WrritenFlog.where(movie_id: params[:id]).reverse_order.page(params[:page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: '会員情報の更新が完了しました。'
    else
      render :edit
    end
  end

  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end

    private

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flogs_helper.rb
module FlogsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/mylists_helper.rb
module MylistsHelper
end

app/helpers/user_lists_helper.rb
module UserListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <%= image_tag("IMG_5784.jpg", class: 'logo mx-auto d-block') %>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Top', root_path, class: 'nav-link text-dark' %>
              </li>
               <li class="nav-item">
                <%= link_to 'Flogs', flogs_path, class: 'nav-link text-dark' %>
               </li>
               <li class="nav-item">
                <%= link_to 'MyLists', mylists_path, class: 'nav-link text-dark' %>
               </li>
               <li class="nav-item">
                <%= link_to 'プロフィール編集', edit_user_path(current_user.id), class: 'nav-link text-dark' %>
               </li>
               <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
               </li>
             <% else %>
                <li class="nav-item">
                  <%= link_to 'Top', root_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                </li>
              <% end %>
          </ul>
        </div>
      </nav>
    </header>

      <main>
        <%= yield %>
      </main>
      
      <footer>
      </footer>
      
    </body>
</html>